version: "3.8"

services:
  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - valkey
    environment:
      - VALKEY_HOST=valkey
      - VALKEY_PORT=6379
  valkey:
    image: valkey/valkey:latest
    restart: always
    ports:
      - "6379:6379"
